### ISSUE TITLE
Eintragen von neuen Lokalitäten

### ISSUE THREAD

**Issue by danez** [smeir/berlin-vegan-guide#53]
Es wäre doch eigentlich super wenn Leute mitmachen könnten und beitragen könnten, mehr Restaurants der Läden hinzuzufügen. Ich finde oft neue Sachen die es in der App noch nicht gibt und ich könnte zwar das json file bearbeiten, aber viele können das halt nicht.

Was hältst du davon?

**Comment by smeir** [comment]
Na,ja ich glaube so viele würden es nicht benutzen, das sich der Aufwand lohnt. Alternativ können uns die Leute über das Formular http://goo.gl/forms/OcW2QhoZ9Y ihre Daten schicken. Unsere eigentliche Datenbank ist ja ein Google Spreadsheet und wir generieren daraus ein JSON. Falls wir die App mal neu schreiben (dann Android nativ) könnte man es aber nochmal überlegen.
