### ISSUE TITLE
Crashes on CM11 without PlayServices

### ISSUE THREAD

**Issue by dktzde** [smeir/Berlin-Vegan-Guide#54]
Hi, I tried the version from F-Droid and from PlayStore. I cannot start it. It crashes at the start-up. I have Android 4.4.4 (Cyanogenmod 11) on an 1gb RAM Smartphone from HTC. I have no PlayServices installed.

**Comment by smeir** [comment]
Unfortunately the app crash if you don't have installed a Network Location Provider. :-( 

If you have F-Droid installed its very easy. Please install the middleware "µg UnifiedNlp" and than a backend. I tested the backend from mozilla and it works. For details please see: http://forum.xda-developers.com/android/apps-games/app-g-unifiednlp-floss-wi-fi-cell-tower-t2991544

You can also try our complete new application, this works also if you have only GPS installed and no play services:

http://berlin-vegan.de/app/releases/bvapp-foss-debug-e6f2.apk
md5sum: afcb22a8301df4578f9aec2923a199b7
